apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-n3ee
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-fkpu-tenant/rhtap-demo-app/hacbs-test-project-n3ee@sha256:78959ba768fc298c70d75d36da5044f9b6897dc402a4b17f309cbb9cf4ce8aaa
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
